<?php
    $overlay  = (array) $this->getOverlaySettings();
    $isCursor = Mage::helper('ajaxloader')->isCursorLoaderEnabled();
    $isMain   = Mage::helper('ajaxloader')->isMainLoaderEnabled();
?>
<script>
    Ajaxloader.setOverlaySettings(
        '<?php echo $overlay['color'] ?>',
        '<?php echo $overlay['opacity'] ?>',
        '<?php echo $overlay['element'] ?>',
        '<?php echo $overlay['loader'] ?>',
        '<?php echo $overlay['loader_opacity'] ?>'
    );
    Ajaxloader.setAnimationSpeed(<?php echo $this->getAnimationSpeed() ?>);
        
    <?php if ($this->isOnload()): ?>
        jQblvg(window).on('beforeunload', function(){
            Ajaxloader.setOverlayElement('.page');
            Ajaxloader.activateOverlay();
            <?php if ($isCursor): ?>
                Ajaxloader.showCursorLoader();
            <?php endif ?>
            <?php if ($isMain): ?>
                Ajaxloader.showMainLoader();
            <?php endif ?>
        });
    <?php endif ?>
    
    if (!Ajaxloader.disabled) {
        jQblvg(document).bind('ajaxStart', function() {
            Ajaxloader.activateOverlay();
            <?php if ($isCursor): ?>
                Ajaxloader.showCursorLoader();
            <?php endif ?>
            <?php if ($isMain): ?>
                Ajaxloader.showMainLoader();
            <?php endif ?>
        });
        
        jQblvg(document).bind('ajaxStop', function() {
            Ajaxloader.disableOverlay();
            <?php if ($isCursor): ?>
                Ajaxloader.hideCursorLoader();
            <?php endif ?>
            <?php if ($isMain): ?>
                Ajaxloader.hideMainLoader();
            <?php endif ?>
        });
    }
</script>
<?php if ($isCursor): ?>
    <script>
        jQblvg.prettyLoader();
    </script>
    <style>
        .prettyLoader {
            background: url('<?php echo $this->getCursorLoaderImage() ?>') center center no-repeat #ffffff;
        }
    </style>
<?php endif ?>